# Generated by Django 4.2 on 2023-07-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colaboradores',
            new_name='Colaborador',
        ),
    ]
